// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/therealpaulgg/ssh-sync-server/pkg/database/repository (interfaces: MachineRepository)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	models "github.com/therealpaulgg/ssh-sync-server/pkg/database/models"
)

// MockMachineRepository is a mock of MachineRepository interface.
type MockMachineRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMachineRepositoryMockRecorder
}

// MockMachineRepositoryMockRecorder is the mock recorder for MockMachineRepository.
type MockMachineRepositoryMockRecorder struct {
	mock *MockMachineRepository
}

// NewMockMachineRepository creates a new mock instance.
func NewMockMachineRepository(ctrl *gomock.Controller) *MockMachineRepository {
	mock := &MockMachineRepository{ctrl: ctrl}
	mock.recorder = &MockMachineRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMachineRepository) EXPECT() *MockMachineRepositoryMockRecorder {
	return m.recorder
}

// CreateMachine mocks base method.
func (m *MockMachineRepository) CreateMachine(arg0 *models.Machine) (*models.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMachine", arg0)
	ret0, _ := ret[0].(*models.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMachine indicates an expected call of CreateMachine.
func (mr *MockMachineRepositoryMockRecorder) CreateMachine(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMachine", reflect.TypeOf((*MockMachineRepository)(nil).CreateMachine), arg0)
}

// CreateMachineTx mocks base method.
func (m *MockMachineRepository) CreateMachineTx(arg0 *models.Machine, arg1 pgx.Tx) (*models.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMachineTx", arg0, arg1)
	ret0, _ := ret[0].(*models.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMachineTx indicates an expected call of CreateMachineTx.
func (mr *MockMachineRepositoryMockRecorder) CreateMachineTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMachineTx", reflect.TypeOf((*MockMachineRepository)(nil).CreateMachineTx), arg0, arg1)
}

// DeleteMachine mocks base method.
func (m *MockMachineRepository) DeleteMachine(arg0 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMachine", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMachine indicates an expected call of DeleteMachine.
func (mr *MockMachineRepositoryMockRecorder) DeleteMachine(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMachine", reflect.TypeOf((*MockMachineRepository)(nil).DeleteMachine), arg0)
}

// GetMachine mocks base method.
func (m *MockMachineRepository) GetMachine(arg0 uuid.UUID) (*models.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachine", arg0)
	ret0, _ := ret[0].(*models.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachine indicates an expected call of GetMachine.
func (mr *MockMachineRepositoryMockRecorder) GetMachine(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachine", reflect.TypeOf((*MockMachineRepository)(nil).GetMachine), arg0)
}

// GetMachineByNameAndUser mocks base method.
func (m *MockMachineRepository) GetMachineByNameAndUser(arg0 string, arg1 uuid.UUID) (*models.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineByNameAndUser", arg0, arg1)
	ret0, _ := ret[0].(*models.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineByNameAndUser indicates an expected call of GetMachineByNameAndUser.
func (mr *MockMachineRepositoryMockRecorder) GetMachineByNameAndUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineByNameAndUser", reflect.TypeOf((*MockMachineRepository)(nil).GetMachineByNameAndUser), arg0, arg1)
}

// GetUserMachines mocks base method.
func (m *MockMachineRepository) GetUserMachines(arg0 uuid.UUID) ([]models.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMachines", arg0)
	ret0, _ := ret[0].([]models.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMachines indicates an expected call of GetUserMachines.
func (mr *MockMachineRepositoryMockRecorder) GetUserMachines(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMachines", reflect.TypeOf((*MockMachineRepository)(nil).GetUserMachines), arg0)
}
