// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/therealpaulgg/ssh-sync-server/pkg/database/repository (interfaces: UserRepository)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	models "github.com/therealpaulgg/ssh-sync-server/pkg/database/models"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// AddAndUpdateConfig mocks base method.
func (m *MockUserRepository) AddAndUpdateConfig(arg0 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAndUpdateConfig", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAndUpdateConfig indicates an expected call of AddAndUpdateConfig.
func (mr *MockUserRepositoryMockRecorder) AddAndUpdateConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAndUpdateConfig", reflect.TypeOf((*MockUserRepository)(nil).AddAndUpdateConfig), arg0)
}

// AddAndUpdateConfigTx mocks base method.
func (m *MockUserRepository) AddAndUpdateConfigTx(arg0 *models.User, arg1 pgx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAndUpdateConfigTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAndUpdateConfigTx indicates an expected call of AddAndUpdateConfigTx.
func (mr *MockUserRepositoryMockRecorder) AddAndUpdateConfigTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAndUpdateConfigTx", reflect.TypeOf((*MockUserRepository)(nil).AddAndUpdateConfigTx), arg0, arg1)
}

// AddAndUpdateKeys mocks base method.
func (m *MockUserRepository) AddAndUpdateKeys(arg0 *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAndUpdateKeys", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAndUpdateKeys indicates an expected call of AddAndUpdateKeys.
func (mr *MockUserRepositoryMockRecorder) AddAndUpdateKeys(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAndUpdateKeys", reflect.TypeOf((*MockUserRepository)(nil).AddAndUpdateKeys), arg0)
}

// AddAndUpdateKeysTx mocks base method.
func (m *MockUserRepository) AddAndUpdateKeysTx(arg0 *models.User, arg1 pgx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAndUpdateKeysTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAndUpdateKeysTx indicates an expected call of AddAndUpdateKeysTx.
func (mr *MockUserRepositoryMockRecorder) AddAndUpdateKeysTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAndUpdateKeysTx", reflect.TypeOf((*MockUserRepository)(nil).AddAndUpdateKeysTx), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockUserRepository) CreateUser(arg0 *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryMockRecorder) CreateUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepository)(nil).CreateUser), arg0)
}

// CreateUserTx mocks base method.
func (m *MockUserRepository) CreateUserTx(arg0 *models.User, arg1 pgx.Tx) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTx", arg0, arg1)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTx indicates an expected call of CreateUserTx.
func (mr *MockUserRepositoryMockRecorder) CreateUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTx", reflect.TypeOf((*MockUserRepository)(nil).CreateUserTx), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockUserRepository) DeleteUser(arg0 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserRepositoryMockRecorder) DeleteUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserRepository)(nil).DeleteUser), arg0)
}

// DeleteUserKeyTx mocks base method.
func (m *MockUserRepository) DeleteUserKeyTx(arg0 *models.User, arg1 uuid.UUID, arg2 pgx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserKeyTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserKeyTx indicates an expected call of DeleteUserKeyTx.
func (mr *MockUserRepositoryMockRecorder) DeleteUserKeyTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserKeyTx", reflect.TypeOf((*MockUserRepository)(nil).DeleteUserKeyTx), arg0, arg1, arg2)
}

// GetUser mocks base method.
func (m *MockUserRepository) GetUser(arg0 uuid.UUID) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserRepositoryMockRecorder) GetUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserRepository)(nil).GetUser), arg0)
}

// GetUserByUsername mocks base method.
func (m *MockUserRepository) GetUserByUsername(arg0 string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", arg0)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserRepositoryMockRecorder) GetUserByUsername(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserRepository)(nil).GetUserByUsername), arg0)
}

// GetUserConfig mocks base method.
func (m *MockUserRepository) GetUserConfig(arg0 uuid.UUID) ([]models.SshConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserConfig", arg0)
	ret0, _ := ret[0].([]models.SshConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserConfig indicates an expected call of GetUserConfig.
func (mr *MockUserRepositoryMockRecorder) GetUserConfig(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserConfig", reflect.TypeOf((*MockUserRepository)(nil).GetUserConfig), arg0)
}

// GetUserKey mocks base method.
func (m *MockUserRepository) GetUserKey(arg0, arg1 uuid.UUID) (*models.SshKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserKey", arg0, arg1)
	ret0, _ := ret[0].(*models.SshKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserKey indicates an expected call of GetUserKey.
func (mr *MockUserRepositoryMockRecorder) GetUserKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserKey", reflect.TypeOf((*MockUserRepository)(nil).GetUserKey), arg0, arg1)
}

// GetUserKeys mocks base method.
func (m *MockUserRepository) GetUserKeys(arg0 uuid.UUID) ([]models.SshKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserKeys", arg0)
	ret0, _ := ret[0].([]models.SshKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserKeys indicates an expected call of GetUserKeys.
func (mr *MockUserRepositoryMockRecorder) GetUserKeys(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserKeys", reflect.TypeOf((*MockUserRepository)(nil).GetUserKeys), arg0)
}
