// Code generated by MockGen. Was modified to work with generics.
// Source: ./pkg/database/query/transaction.go

// Package query is a generated GoMock package.
package query

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v5 "github.com/jackc/pgx/v5"
)

// MockQueryServiceTx is a mock of QueryServiceTx interface.
type MockQueryServiceTx[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockQueryServiceTxMockRecorder[T]
}

// MockQueryServiceTxMockRecorder is the mock recorder for MockQueryServiceTx.
type MockQueryServiceTxMockRecorder[T any] struct {
	mock *MockQueryServiceTx[T]
}

// NewMockQueryServiceTx creates a new mock instance.
func NewMockQueryServiceTx[T any](ctrl *gomock.Controller) *MockQueryServiceTx[T] {
	mock := &MockQueryServiceTx[T]{ctrl: ctrl}
	mock.recorder = &MockQueryServiceTxMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryServiceTx[T]) EXPECT() *MockQueryServiceTxMockRecorder[T] {
	return m.recorder
}

// Commit mocks base method.
func (m *MockQueryServiceTx[T]) Commit(tx v5.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockQueryServiceTxMockRecorder[T]) Commit(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockQueryServiceTx[T])(nil).Commit), tx)
}

// Insert mocks base method.
func (m *MockQueryServiceTx[T]) Insert(tx v5.Tx, query string, args ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{tx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Insert", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockQueryServiceTxMockRecorder[T]) Insert(tx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockQueryServiceTx[T])(nil).Insert), varargs...)
}

// Query mocks base method.
func (m *MockQueryServiceTx[T]) Query(tx v5.Tx, query string, args ...interface{}) ([]T, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{tx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockQueryServiceTxMockRecorder[T]) Query(tx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockQueryServiceTx[T])(nil).Query), varargs...)
}

// QueryOne mocks base method.
func (m *MockQueryServiceTx[T]) QueryOne(tx v5.Tx, query string, args ...interface{}) (*T, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{tx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryOne", varargs...)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryOne indicates an expected call of QueryOne.
func (mr *MockQueryServiceTxMockRecorder[T]) QueryOne(tx, query interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryOne", reflect.TypeOf((*MockQueryServiceTx[T])(nil).QueryOne), varargs...)
}

// Rollback mocks base method.
func (m *MockQueryServiceTx[T]) Rollback(tx v5.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockQueryServiceTxMockRecorder[T]) Rollback(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockQueryServiceTx[T])(nil).Rollback), tx)
}

// StartTx mocks base method.
func (m *MockQueryServiceTx[T]) StartTx(options v5.TxOptions) (v5.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTx", options)
	ret0, _ := ret[0].(v5.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartTx indicates an expected call of StartTx.
func (mr *MockQueryServiceTxMockRecorder[T]) StartTx(options interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTx", reflect.TypeOf((*MockQueryServiceTx[T])(nil).StartTx), options)
}
