version: '3.3'
services:
    ssh-sync-server:
        restart: always
        environment:
          - PORT=3000
          - NO_DOTENV=1
          - DATABASE_USERNAME=sshsync
          - DATABASE_PASSWORD=sshsync
          - DATABASE_NAME=sshsync
          - DATABASE_HOST=ssh-sync-db:5432
        logging:
          driver: json-file
          options:
            max-size: 10m
        ports:
          - '3000:3000'
        image: b44427a64de93c20123c068387b0adc0434434ba709fbd91dd03d33ade489c3e
        container_name: sshdbg
    ssh-sync-db:
        image: therealpaulgg/ssh-sync-db:latest 
        container_name: ssh-sync-db-debug
        environment:
          - POSTGRES_USER=sshsync
          - POSTGRES_PASSWORD=sshsync
          - POSTGRES_DB=sshsync
        restart: always
    ssh-sync:
        image: 62eab8fb32b34e0a2cf36e8635d810c20a38baa2d7beaf5b6918139339e23c23
        container_name: ssh-sync
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
    ssh-sync-2:
        image: 62eab8fb32b34e0a2cf36e8635d810c20a38baa2d7beaf5b6918139339e23c23
        container_name: ssh-sync-2
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
    ssh-sync-3:
        image: 62eab8fb32b34e0a2cf36e8635d810c20a38baa2d7beaf5b6918139339e23c23
        container_name: ssh-sync-3
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
        #http://ssh-sync-server-debug:3000