version: '3.3'
services:
    ssh-sync-server:
        restart: always
        environment:
          - PORT=3000
          - NO_DOTENV=1
          - DATABASE_USERNAME=sshsync
          - DATABASE_PASSWORD=sshsync
          - DATABASE_NAME=sshsync
          - DATABASE_HOST=ssh-sync-db:5432
        logging:
          driver: json-file
          options:
            max-size: 10m
        ports:
          - '3000:3000'
        image: therealpaulgg/ssh-sync-server 
        container_name: ssh-sync-server
    ssh-sync-db:
        image: therealpaulgg/ssh-sync-db:latest 
        container_name: ssh-sync-db-debug
        environment:
          - POSTGRES_USER=sshsync
          - POSTGRES_PASSWORD=sshsync
          - POSTGRES_DB=sshsync
        restart: always
    ssh-sync:
        image: 2d277cde6d3ba4b20c2743a62000be589ad767febc24bf04b33106285d7c0457
        container_name: ssh-sync
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
    ssh-sync-2:
        image: 2d277cde6d3ba4b20c2743a62000be589ad767febc24bf04b33106285d7c0457
        container_name: ssh-sync-2
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
    ssh-sync-3:
        image: 2d277cde6d3ba4b20c2743a62000be589ad767febc24bf04b33106285d7c0457
        container_name: ssh-sync-3
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
