version: '3.3'
services:
    ssh-sync-server:
        restart: always
        environment:
          - PORT=3000
          - NO_DOTENV=1
          - DATABASE_USERNAME=sshsync
          - DATABASE_PASSWORD=sshsync
          - DATABASE_NAME=sshsync
          - DATABASE_HOST=ssh-sync-db:5432
        logging:
          driver: json-file
          options:
            max-size: 10m
        ports:
          - '3000:3000'
        image: 856da056de3abb7b317e59481bd500c27eb0f3b2a4c2432e8db930c1d20e71bf
        container_name: ssh-sync-server-debug
    ssh-sync-db:
        image: therealpaulgg/ssh-sync-db:latest 
        container_name: ssh-sync-db-debug
        environment:
          - POSTGRES_USER=sshsync
          - POSTGRES_PASSWORD=sshsync
          - POSTGRES_DB=sshsync
        restart: always
    ssh-sync:
        image: 9065faaa7a20a821f7323f42cbddac1b594f7d01d57f8b2a2837e433769b86f4
        container_name: ssh-sync
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
    ssh-sync-2:
        image: 9065faaa7a20a821f7323f42cbddac1b594f7d01d57f8b2a2837e433769b86f4
        container_name: ssh-sync-2
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
    ssh-sync-3:
        image: 9065faaa7a20a821f7323f42cbddac1b594f7d01d57f8b2a2837e433769b86f4
        container_name: ssh-sync-3
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
        #http://ssh-sync-server-debug:3000