version: '3.3'
services:
    ssh-sync-server:
        restart: always
        environment:
          - PORT=3000
          - NO_DOTENV=1
          - DATABASE_USERNAME=sshsync
          - DATABASE_PASSWORD=sshsync
          - DATABASE_NAME=sshsync
          - DATABASE_HOST=ssh-sync-db:5432
        logging:
          driver: json-file
          options:
            max-size: 10m
        ports:
          - '3000:3000'
        image: ssh-sync-server-prerelease
        container_name: ssh-sync-server
    ssh-sync-db:
        image: therealpaulgg/ssh-sync-db:latest 
        container_name: ssh-sync-db-debug
        environment:
          - POSTGRES_USER=sshsync
          - POSTGRES_PASSWORD=sshsync
          - POSTGRES_DB=sshsync
        restart: always
    ssh-sync:
        image: ssh-debug
        container_name: ssh-sync
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
        volumes:
          - ssh-sync-volume:/root
    ssh-sync-2:
        image: ssh-debug
        container_name: ssh-sync-2
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
        volumes:
          - ssh-sync-2-volume:/root
    ssh-sync-3:
        image: ssh-debug
        container_name: ssh-sync-3
        stdin_open: true # Allows Docker container to keep STDIN open
        tty: true # Allocates a pseudo-TTY
        volumes:
          - ssh-sync-3-volume:/root

volumes:
  ssh-sync-volume:
  ssh-sync-2-volume:
  ssh-sync-3-volume: