// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/database/repository/known_host.go

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
	models "github.com/therealpaulgg/ssh-sync-server/pkg/database/models"
)

// MockKnownHostRepository is a mock of KnownHostRepository interface.
type MockKnownHostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKnownHostRepositoryMockRecorder
}

// MockKnownHostRepositoryMockRecorder is the mock recorder for MockKnownHostRepository.
type MockKnownHostRepositoryMockRecorder struct {
	mock *MockKnownHostRepository
}

// NewMockKnownHostRepository creates a new mock instance.
func NewMockKnownHostRepository(ctrl *gomock.Controller) *MockKnownHostRepository {
	mock := &MockKnownHostRepository{ctrl: ctrl}
	mock.recorder = &MockKnownHostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKnownHostRepository) EXPECT() *MockKnownHostRepositoryMockRecorder {
	return m.recorder
}

// UpsertKnownHost mocks base method.
func (m *MockKnownHostRepository) UpsertKnownHost(entry *models.KnownHost) (*models.KnownHost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertKnownHost", entry)
	ret0, _ := ret[0].(*models.KnownHost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertKnownHost indicates an expected call of UpsertKnownHost.
func (mr *MockKnownHostRepositoryMockRecorder) UpsertKnownHost(entry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertKnownHost", reflect.TypeOf((*MockKnownHostRepository)(nil).UpsertKnownHost), entry)
}

// UpsertKnownHostTx mocks base method.
func (m *MockKnownHostRepository) UpsertKnownHostTx(entry *models.KnownHost, tx pgx.Tx) (*models.KnownHost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertKnownHostTx", entry, tx)
	ret0, _ := ret[0].(*models.KnownHost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertKnownHostTx indicates an expected call of UpsertKnownHostTx.
func (mr *MockKnownHostRepositoryMockRecorder) UpsertKnownHostTx(entry, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertKnownHostTx", reflect.TypeOf((*MockKnownHostRepository)(nil).UpsertKnownHostTx), entry, tx)
}
