// Code generated by MockGen. DO NOT EDIT.
// Source: machine.go
//
// Generated by this command:
//
//	mockgen -source=machine.go -destination=machinemock.go -package=repository
//

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	models "github.com/therealpaulgg/ssh-sync-server/pkg/database/models"
	gomock "go.uber.org/mock/gomock"
)

// MockMachineRepository is a mock of MachineRepository interface.
type MockMachineRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMachineRepositoryMockRecorder
	isgomock struct{}
}

// MockMachineRepositoryMockRecorder is the mock recorder for MockMachineRepository.
type MockMachineRepositoryMockRecorder struct {
	mock *MockMachineRepository
}

// NewMockMachineRepository creates a new mock instance.
func NewMockMachineRepository(ctrl *gomock.Controller) *MockMachineRepository {
	mock := &MockMachineRepository{ctrl: ctrl}
	mock.recorder = &MockMachineRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMachineRepository) EXPECT() *MockMachineRepositoryMockRecorder {
	return m.recorder
}

// CreateMachine mocks base method.
func (m *MockMachineRepository) CreateMachine(machine *models.Machine) (*models.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMachine", machine)
	ret0, _ := ret[0].(*models.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMachine indicates an expected call of CreateMachine.
func (mr *MockMachineRepositoryMockRecorder) CreateMachine(machine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMachine", reflect.TypeOf((*MockMachineRepository)(nil).CreateMachine), machine)
}

// CreateMachineTx mocks base method.
func (m *MockMachineRepository) CreateMachineTx(machine *models.Machine, tx pgx.Tx) (*models.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMachineTx", machine, tx)
	ret0, _ := ret[0].(*models.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMachineTx indicates an expected call of CreateMachineTx.
func (mr *MockMachineRepositoryMockRecorder) CreateMachineTx(machine, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMachineTx", reflect.TypeOf((*MockMachineRepository)(nil).CreateMachineTx), machine, tx)
}

// DeleteMachine mocks base method.
func (m *MockMachineRepository) DeleteMachine(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMachine", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMachine indicates an expected call of DeleteMachine.
func (mr *MockMachineRepositoryMockRecorder) DeleteMachine(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMachine", reflect.TypeOf((*MockMachineRepository)(nil).DeleteMachine), id)
}

// GetMachine mocks base method.
func (m *MockMachineRepository) GetMachine(id uuid.UUID) (*models.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachine", id)
	ret0, _ := ret[0].(*models.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachine indicates an expected call of GetMachine.
func (mr *MockMachineRepositoryMockRecorder) GetMachine(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachine", reflect.TypeOf((*MockMachineRepository)(nil).GetMachine), id)
}

// GetMachineByNameAndUser mocks base method.
func (m *MockMachineRepository) GetMachineByNameAndUser(machineName string, userID uuid.UUID) (*models.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineByNameAndUser", machineName, userID)
	ret0, _ := ret[0].(*models.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineByNameAndUser indicates an expected call of GetMachineByNameAndUser.
func (mr *MockMachineRepositoryMockRecorder) GetMachineByNameAndUser(machineName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineByNameAndUser", reflect.TypeOf((*MockMachineRepository)(nil).GetMachineByNameAndUser), machineName, userID)
}

// GetUserMachines mocks base method.
func (m *MockMachineRepository) GetUserMachines(id uuid.UUID) ([]models.Machine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMachines", id)
	ret0, _ := ret[0].([]models.Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMachines indicates an expected call of GetUserMachines.
func (mr *MockMachineRepositoryMockRecorder) GetUserMachines(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMachines", reflect.TypeOf((*MockMachineRepository)(nil).GetUserMachines), id)
}

// UpdateMachineKeys mocks base method.
func (m *MockMachineRepository) UpdateMachineKeys(id uuid.UUID, publicKey, encapsulationKey []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMachineKeys", id, publicKey, encapsulationKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMachineKeys indicates an expected call of UpdateMachineKeys.
func (mr *MockMachineRepositoryMockRecorder) UpdateMachineKeys(id, publicKey, encapsulationKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMachineKeys", reflect.TypeOf((*MockMachineRepository)(nil).UpdateMachineKeys), id, publicKey, encapsulationKey)
}
