// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/database/repository/master_key_rotation.go

// Package repository is a generated GoMock package.
package repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	models "github.com/therealpaulgg/ssh-sync-server/pkg/database/models"
)

// MockMasterKeyRotationRepository is a mock of MasterKeyRotationRepository interface.
type MockMasterKeyRotationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMasterKeyRotationRepositoryMockRecorder
}

// MockMasterKeyRotationRepositoryMockRecorder is the mock recorder for MockMasterKeyRotationRepository.
type MockMasterKeyRotationRepositoryMockRecorder struct {
	mock *MockMasterKeyRotationRepository
}

// NewMockMasterKeyRotationRepository creates a new mock instance.
func NewMockMasterKeyRotationRepository(ctrl *gomock.Controller) *MockMasterKeyRotationRepository {
	mock := &MockMasterKeyRotationRepository{ctrl: ctrl}
	mock.recorder = &MockMasterKeyRotationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMasterKeyRotationRepository) EXPECT() *MockMasterKeyRotationRepositoryMockRecorder {
	return m.recorder
}

// UpsertRotationTx mocks base method.
func (m *MockMasterKeyRotationRepository) UpsertRotationTx(tx pgx.Tx, machineID uuid.UUID, encKey []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRotationTx", tx, machineID, encKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRotationTx indicates an expected call of UpsertRotationTx.
func (mr *MockMasterKeyRotationRepositoryMockRecorder) UpsertRotationTx(tx, machineID, encKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRotationTx", reflect.TypeOf((*MockMasterKeyRotationRepository)(nil).UpsertRotationTx), tx, machineID, encKey)
}

// GetRotationForMachine mocks base method.
func (m *MockMasterKeyRotationRepository) GetRotationForMachine(machineID uuid.UUID) (*models.MasterKeyRotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRotationForMachine", machineID)
	ret0, _ := ret[0].(*models.MasterKeyRotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRotationForMachine indicates an expected call of GetRotationForMachine.
func (mr *MockMasterKeyRotationRepositoryMockRecorder) GetRotationForMachine(machineID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRotationForMachine", reflect.TypeOf((*MockMasterKeyRotationRepository)(nil).GetRotationForMachine), machineID)
}

// DeleteRotationForMachine mocks base method.
func (m *MockMasterKeyRotationRepository) DeleteRotationForMachine(machineID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRotationForMachine", machineID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRotationForMachine indicates an expected call of DeleteRotationForMachine.
func (mr *MockMasterKeyRotationRepositoryMockRecorder) DeleteRotationForMachine(machineID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRotationForMachine", reflect.TypeOf((*MockMasterKeyRotationRepository)(nil).DeleteRotationForMachine), machineID)
}

var _ MasterKeyRotationRepository = (*MockMasterKeyRotationRepository)(nil)
